services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: mvpguide_postgres
    environment:
      POSTGRES_DB: excursion_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5450:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres_auth:
    image: postgis/postgis:16-3.4
    container_name: adminpanel_postgres_auth
    environment:
      POSTGRES_DB: adminpanel_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5451:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2025-04-08T15-41-24Z
    container_name: mvpguide_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: your_access_key
      MINIO_ROOT_PASSWORD: your_secret_key
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  postgres_data:
  postgres_auth_data:
  minio_data: